theme: jekyll-theme-cayman
title : [Provisional Machine Learning Results]
description : [This is a temporary site to log important results of exploratory Data analysis done on the amazon-rivers dataset]
